### ISSUE TITLE
Establish convention for calling registerComponentManager

### ISSUE THREAD

**Issue by dgeb** [glimmerjs/glimmer-application#16]
From a [comment](https://github.com/glimmerjs/glimmer-application/pull/15#issuecomment-287175293) by @robbiepitts:

> What does the intended usage of registerComponentManager look like? The Environment class is imported in application.ts and registered manually in Application#initialize (which is ultimately called from the constructor). Then when Application#boot happens the container is set up, Application#env is assigned, and the app is rendered. This all means that, as far as I can tell, we cannot registerComponentManager before Application is instantiated, after it is instantiated and before boot, or after boot.

> Also wondering if it would make sense to incorporate component managers into the DI system? Then we can just look them up and don't have to worry about registering.

**Comment by robbiepitts** [comment]
hello-glimmer is currently broken with the master of @glimmer/application (and @glimmer/component and @glimmer/application-pipeline) linked in because you _must_ call `registerComponentManager` for the app to boot, but there is no way to do that that I can see.

The error:

<img width="900" alt="screen shot 2017-03-20 at 9 00 54 am" src="https://cloud.githubusercontent.com/assets/671032/24100720/c64ca722-0d4b-11e7-817a-e6338cc4ccf4.png">

And here's what requires that `registerComponentManager` be called:

```typescript
registerComponent(name: string, componentSpecifier: string, meta: TemplateMeta, owner: Owner): ComponentDefinition<Component> {
  // ...
  let manager: ComponentManager<Component> | ComponentDefinitionCreator = meta.managerId ? this.componentManagers[meta.managerId] : this.defaultComponentManager;
  // ...
```

For convenience here is what `registerComponentManager` looks like:

```typescript
registerComponentManager(manager: ComponentManager<Component>, identifier: string, isDefaultComponentManager = false) {
  this.componentManagers[identifier] = manager;
  if (isDefaultComponentManager) {
    this.defaultComponentManager = manager;
  }
}
```

**Comment by robbiepitts** [comment]
Should be fixed by https://github.com/glimmerjs/glimmer-application/pull/17.

**Comment by robbiepitts** [comment]
We can close this now @dgeb :)

**Comment by dgeb** [comment]
Woot!
