### ISSUE TITLE
`if` helper inline form not working

### ISSUE THREAD

**Issue by mmun** [glimmerjs/glimmer-application#42]
`{{if foo bar baz}}` and `(if foo bar baz)` produce the error
```
Uncaught Error: Compile Error: if is not a helper
```

**Comment by GavinJoyce** [comment]
Is there a way for us to extract [some shared helpers](https://github.com/emberjs/ember.js/tree/master/packages/ember-glimmer/lib/helpers) from ember so that we can use them in both ember and glimmer? Could we share [inline if-unless](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/helpers/if-unless.js) for example?

**Comment by locks** [comment]
This has been addressed, thank you :)
