### ISSUE TITLE
Things That Need To Be Fixed

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer-application#54]
This is an ongoing list of stuff that I'm finding that have discovered in trying to work on this.

## Build

- [ ] No confidence in types at build/publish time
- [ ] Build seems pretty slow for the amount of files
- [ ] Extract `GlimmerTemplateCompiler`
- [ ] le sourcemaps

## Test Suite

- [ ] Test suite should have more exhaustive rendering tests, similar to [Ember's](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/tests/integration/application/rendering-test.js)
- [ ] `ember serve` should run the tests
- [ ] Unclear how to test end-to-end typical application with `Component` and `@tracked`
- [ ]  Tests don't update

**Comment by robbiepitts** [comment]
Re: extracting `GlimmerTemplateCompiler`. I believe I spoke to someone about moving that upstream into @glimmer/compiler after making it more generic. For example, specifier generation is hard-coded right now.

**Comment by robbiepitts** [comment]
Also, some rendering tests are WIP in https://github.com/glimmerjs/glimmer-application/pull/40.

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
