### ISSUE TITLE
Sourcemaps seem to have issues

### ISSUE THREAD

**Issue by wycats** [glimmerjs/glimmer-application#56]
A number of people have reported problems with source maps, and many contributors have experienced the problem.

If you experience issues, please reply to this issue with more information. The more the better at this point.

**Comment by mattmarcum** [comment]
Out of the box I can't set breakpoints in the typescript sourcemaps that ship with the build.  When I try to go to `app.js` and set a breakpoint there, chrome tries to redirect to the right sourcemap but usually I end up in `component-manager.ts`.  I'd like the option to generate javascript es6 source maps.

**Comment by Kuzirashi** [comment]
When I put debugger in Typescript code - Chrome stops execution of code, but, it highlights wrong line of code (not the one with debugger statement in it). Sourcemaps are inaccurate which makes line-by-line debugging impossible. I can only use console to debug my code and look into an IDE to see where I really am (instead of looking at Chrome debugger). It's crucial for development workflow to have accurate sourcemaps. :)

**Comment by peabnuts123** [comment]
I assume this is well-known but just to add my two-cents, I can confirm that sourcemaps seem to be completely inoperational. Upon generating a new glimmer project and inspecting the default component only some lines can have breakpoints added to them. 

![image](https://user-images.githubusercontent.com/2322840/33972541-29617c5a-e0e3-11e7-9b36-ec64afa205ea.png)

See that in my small example app (displaying a list of "car" objects) I can only put breakpoints on lines 16, 25, 26, 32, 33, 35, 39, 43 and 48. Changing `inlineSourceMap` to `false` in tsconfig.json does not change anything. 

![image](https://user-images.githubusercontent.com/2322840/33972619-93adb600-e0e3-11e7-8605-2f553269cb31.png)

Subsequently, if I actually put a breakpoint somewhere in this, it does not seem to correspond to the correct symbols in the source file. For example, in this screenshot you can see that the variable `stringLength` is `undefined` despite the right-hand-side always returning a number. 

I assume this is mostly TypeScript's doing, as interfaces and the like are entirely used for compilation purposes and do not represent any real code upon being emitted.

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
