### ISSUE TITLE
Accessing ENV

### ISSUE THREAD

**Issue by remzr7** [glimmerjs/glimmer-application#60]
How would one go about accessing ENV?

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
