### ISSUE TITLE
`renderComponent` doesn't accept args or attributes

### ISSUE THREAD

**Issue by robbiepitts** [glimmerjs/glimmer-application#71]
Current signature:

```typescript
renderComponent(
  component: string | ComponentDefinition<Component>,
  parent: Simple.Node,
  nextSibling: Option<Simple.Node> = null
): void
```

Proposed new signature:

```typescript
interface RenderComponentOptions {
  nextSibling?: Option<Simple.Node>;
  args?: Dict<any>;
  attributes?: Dict<string>;
}

renderComponent(
  component: string | ComponentDefinition<Component>,
  parent: Simple.Node,
  options: RenderComponentOptions = {}
): void
```

**Comment by CvX** [comment]
@robbiepitts any progress on this feature? I'd like to help out any way possible.
So far I've made a terrible hack to allow passing args to renderComponent, by (mis)using 😅 `ComponentManager.prepareArgs` (https://github.com/CvX/glimmer-application/commit/c67237706b45815ef66fc164587f7a18d5375a54 though this still doesn't allow setting attributes on components). 
Btw, you can hit me up on Ember Slack if you'd like to discuss this issue in depth.

**Comment by robbiepitts** [comment]
@CvX This is great! Would love help. I've been working on testing stuff recently and have not been working on this.

Could you PR the @glimmer/application stuff (with method signature that matches the above) and move the `prepareArgs` stuff to here https://github.com/glimmerjs/glimmer-component/blob/master/src/component-manager.ts#L82 ? And could you explain to me what you have `prepareArgs` doing? Or maybe if you just PR it I can look at the type info and figure it out. I'm wondering if it is a change that can be made to the default component manager or if we're going to need a separate component manager.

Passing attributes might require a change to the VM. Unsure.

Feel free to holler at me on #dev-glimmer about this.

**Comment by CvX** [comment]
Alright, I've added `RenderComponentOptions` and made some minor changes to [the code](https://github.com/glimmerjs/glimmer-application/compare/master...CvX:render-component-args-hack).
I'm not extracting `prepareArgs` just yet because it may or may not have a flaw. 😉 

What it does:
when called from [VM's PrepareArgs](https://github.com/glimmerjs/glimmer-vm/blob/933acfb16363e45f177b84de51e24509894f42a4/packages/%40glimmer/runtime/lib/compiled/opcodes/component.ts#L63) instead of returning null (default behavior in glimmer-component's componentManager) it checks whether there is a single positional argument named 'args' passed to the component [[1]](https://github.com/CvX/glimmer-application/blob/6cfd6f7b886f73cb0431a6180f9cec11dfcd10dc/src/environment.ts#L108-L115). If so, it returns a new set of arguments [[2]](https://github.com/CvX/glimmer-application/blob/6cfd6f7b886f73cb0431a6180f9cec11dfcd10dc/src/environment.ts#L117-L125).

A potential issue: if component happens to use positional arguments (though I'm not sure if that's even possible with glimmer components) there could be a collision if first argument is named "args".

About passing attributes - maybe a hook similar to `prepareArgs` (but for attrs) could be useful. 🤷‍♂️ tbh I still haven't wrapped my head around attrs handling in the VM.
